"""CMD-DS3: reference scene(events, t) for the live monitor golden files.

Stdlib only. Derives the scene *semantics* (not pixels) from MonitorEvents
(docs/data-model.md 7.2) using design/encoding.json, so design/golden/*.json
can be regenerated byte-identically:

    python3 -m design.golden.reference          # write design/golden/t*.json
    python3 -m design.golden.reference --check  # exit 1 if any file differs

t is milliseconds since the first event's observed_at (event time, motion.md 1).
An event is in the scene when observed_at <= origin + t. Ties keep seq order.
"""
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RECORDING = "fixtures/monitor/recording.jsonl"
ENCODING = "design/encoding.json"
GOLDEN_DIR = ROOT / "design/golden"
SCHEMA = "gc-golden-scene/1"
# One t per step of fixtures/monitor/script.json, plus a late frame after the words expire.
T_MS = (0, 1000, 2000, 3000, 4000, 5000, 7000, 8000, 9000, 12000)

RING_BY_STATUS = {"failed": "failed", "needs_judgement": "needs_judgement", "budget": "budget"}
DROPPED_SHOW_MS = 1000


def load_encoding(root=ROOT):
    return json.loads((root / ENCODING).read_text(encoding="utf-8"))


def load_events(path):
    lines = Path(path).read_text(encoding="utf-8").splitlines()
    return [json.loads(x) for x in lines if x.strip()]


def _ms(iso):
    dt = datetime.strptime(iso, "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=timezone.utc)
    return int(dt.timestamp() * 1000)


def _ring(data):
    status = data.get("status")
    if status in RING_BY_STATUS:
        return RING_BY_STATUS[status]
    if status == "done":
        return "verified" if data.get("verified") else "needs_judgement"
    return "none"


def _edge_weight(pi_permille, lo, hi):
    """pi_permille 0..1000 -> lo..hi px, rounded half up (encoding figures.edge_weight_px)."""
    return lo + ((hi - lo) * pi_permille + 500) // 1000


def _tempo_permille(mood):
    if mood["all_done"]:
        return 0
    if mood["stall"]:
        return 300
    tempo = 500 + min(mood["pace"], 30) * 50
    if mood["tension"]:
        tempo = tempo * 1500 // 1000
    return tempo


def _lightness_delta(mood, rules):
    if mood["all_done"]:
        return rules["all_done"]["lightness_delta_pct"]
    if mood["stall"]:
        return rules["stall"]["lightness_delta_pct"]
    delta = 0
    for name in ("tension", "collaboration"):
        if mood[name]:
            delta += rules[name]["lightness_delta_pct"]
    return delta


def scene(events, t_ms, enc):
    """Scene semantics at t_ms (ms since the first event). Pure: same input, same output."""
    events = sorted(events, key=lambda e: e["seq"])
    origin = _ms(events[0]["observed_at"]) if events else 0
    now = origin + t_ms
    sig = {s["signal"]: s for s in enc["signals"]}
    states = enc["figures"]["states"]
    word_max = enc["word_style"]["max_on_stage_ms"]
    ew = enc["figures"]["edge_weight_px"]

    roles, rnd = [], 0
    figures, tiles, edges, dropped = {}, {}, {}, []
    mood = {"pace": 0, "collaboration": False, "tension": False, "stall": False, "all_done": False}
    last_word = {}  # node -> (observed_ms, seq, word)

    def fig(node, role=None):
        f = figures.setdefault(node, {"node": node, "role": role, "state": "running", "ring": "none",
                                      "item": None, "tether_to": None, "outcome": None})
        if role and not f["role"]:
            f["role"] = role
        return f

    def edge(a, b):
        key = tuple(sorted((a, b)))
        return edges.setdefault(key, {"a": key[0], "b": key[1], "pi_permille": 0, "messages": 0})

    for e in events:
        at = _ms(e["observed_at"])
        if at > now:
            break
        k, d, node = e["kind"], e.get("data") or {}, e.get("node")
        if k == "file:pool.round":
            roles, rnd = list(d.get("roles") or roles), d.get("round", rnd)
        elif k == "file:queue.added":
            tiles[e["item"]] = {"id": e["item"], "role": e.get("role"), "shelf": "waiting",
                                "holder": None, "parent": d.get("parent")}
        elif k == "file:pool.live.claimed":
            f = fig(node, e.get("role"))
            f["item"] = e["item"]
            if f["state"] not in ("retiring", "retired"):
                f["state"] = "running"
            t = tiles.setdefault(e["item"], {"id": e["item"], "role": e.get("role"), "shelf": "waiting",
                                             "holder": None, "parent": None})
            t["shelf"], t["holder"] = "held", node
        elif k == "l0:node.started":
            f = fig(node, e.get("role"))
            f["item"] = e.get("item") or f["item"]
        elif k in ("file:queue.done", "file:queue.failed", "l0:work.failed"):
            tid = d.get("id") if k != "l0:work.failed" else e.get("item")
            t = tiles.get(tid)
            if t:
                t["shelf"] = "done" if k == "file:queue.done" else "failed"
        elif k == "l0:work.accepted":
            child = tiles.get(d.get("id"))
            if child and child["parent"] is None:
                child["parent"] = e.get("item")
        elif k == "l0:work.dropped":
            dropped.append((at, d.get("id")))
        elif k == "file:node.state.consults":
            f = fig(node)
            peers = d.get("peers") or []
            if peers:
                f["state"], f["tether_to"] = "waiting_peer", peers[0]
            elif f["state"] == "waiting_peer":
                f["state"], f["tether_to"] = "running", None
        elif k == "file:node.run.cont_open":
            f = fig(node)
            if f["state"] in ("running", "idle"):
                f["state"] = "continuing"
        elif k == "file:pool.live.idle":
            f = fig(node)
            if f["state"] not in ("retiring", "retired"):
                f["state"] = "idle"
        elif k == "file:pool.live.retiring":
            f = fig(node)
            if f["state"] != "retired":
                f["state"] = "retiring"
        elif k == "l0:node.retired":
            f = fig(node, e.get("role"))
            f["state"], f["tether_to"], f["outcome"] = "retired", None, d.get("outcome")
        elif k == "file:node.state.done":
            fig(node)["ring"] = _ring(d)
        elif k == "file:node.pi":
            edge(node, e["peer"])["pi_permille"] = int(d.get("pi_permille", 0))
        elif k == "l0:peer.message.sent":
            edge(node, e["peer"])["messages"] += 1
        elif k.startswith("derived:"):
            name = k.split(":", 1)[1]
            if name in mood:
                v = d.get("value")
                mood[name] = int(v) if name == "pace" else bool(v)

        word = (sig.get(k) or {}).get("word")
        if k == "file:node.state.consults" and not d.get("peers"):
            word = None  # tether released: nothing to wait on
        if word:
            holder = node
            if holder is None and e.get("item") in tiles:
                holder = tiles[e["item"]]["holder"]
            if holder is not None and sig[k]["target"] != "stage":
                last_word[holder] = (at, e["seq"], word)

    stage_word = None
    for name in enc["word_style"]["sticky_while_true"]:
        mname = name.split(":", 1)[1]
        if mood[mname]:
            stage_word = enc["moods"]["rules"][mname]["word"]
            break

    out_figs = []
    for node in sorted(figures):
        f = figures[node]
        idx = roles.index(f["role"]) if f["role"] in roles else 0
        shapes = enc["figures"]["shapes"]
        w = last_word.get(node)
        out_figs.append({
            "node": node,
            "role": f["role"],
            "shape_index": idx,
            "shape": shapes[idx % len(shapes)],
            "notches": idx // len(shapes),
            "state": f["state"],
            "lightness_pct": states[f["state"]]["lightness_pct"],
            "ring": f["ring"],
            "ring_shape": enc["figures"]["rings"][f["ring"]]["shape"],
            "item": f["item"] if f["state"] != "retired" else None,
            "tether_to": f["tether_to"],
            "outcome_mark": enc["figures"]["retired_outcome_marks"].get(f["outcome"]) if f["state"] == "retired" else None,
            "word": w[2] if w and now - w[0] < word_max else None,
        })

    out_tiles = []
    for tid in sorted(tiles):
        t = tiles[tid]
        out_tiles.append({"id": tid, "role": t["role"], "shelf": t["shelf"],
                          "band": enc["tiles"]["shelves"][t["shelf"]] if t["shelf"] != "held" else None,
                          "holder": t["holder"] if t["shelf"] == "held" else None,
                          "parent": t["parent"],
                          "shape": enc["tiles"]["shapes"][t["shelf"]]})

    out_edges = [dict(v, weight_px=_edge_weight(v["pi_permille"], ew["min"], ew["max"]))
                 for _, v in sorted(edges.items())]

    active = next((m for m in enc["moods"]["priority"] if m != "pace" and mood[m]), "pace")
    words = sorted({f["word"] for f in out_figs if f["word"]} | ({stage_word} if stage_word else set()))
    return {
        "schema": SCHEMA,
        "t_ms": t_ms,
        "round": rnd,
        "figures": out_figs,
        "tiles": out_tiles,
        "dropped_marks": sorted(i for a, i in dropped if now - a < DROPPED_SHOW_MS),
        "edges": out_edges,
        "mood": dict(mood, active=active, tempo_permille=_tempo_permille(mood),
                     lightness_delta_pct=_lightness_delta(mood, enc["moods"]["rules"])),
        "stage_word": stage_word,
        "words": words,
    }


def render(doc):
    return json.dumps(doc, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def golden_files(root=ROOT):
    """{filename: text} for every golden scene of the fixture recording."""
    rec = root / RECORDING
    events = load_events(rec)
    enc = load_encoding(root)
    digest = hashlib.sha256(rec.read_bytes()).hexdigest()
    out = {}
    for t in T_MS:
        doc = scene(events, t, enc)
        doc["recording"] = {"path": RECORDING, "sha256": digest}
        out[f"t{t:05d}.json"] = render(doc)
    return out


def main(argv):
    files = golden_files()
    if "--check" in argv:
        bad = [n for n, txt in files.items()
               if not (GOLDEN_DIR / n).exists() or (GOLDEN_DIR / n).read_text(encoding="utf-8") != txt]
        for n in bad:
            print(f"golden differs: design/golden/{n}")
        return 1 if bad else 0
    for n, txt in files.items():
        (GOLDEN_DIR / n).write_text(txt, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
