#!/usr/bin/env python3
"""Write ./.env for local development with values generated on this machine (CMD-GC50).

Refuses to overwrite an existing file and never prints a generated value. The result is for a developer machine only;
.env stays git-ignored. Usage: python3 scripts/dev_env.py [--path .env] [--db-host db]
"""
from __future__ import annotations

import argparse
import base64
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KEK_ID = "dev"
PATTERN_LINE = "GC_KEK_<id>"


def example_names(text: str) -> list[str]:
    """Names in .env.example, in file order, minus the GC_KEK_<id> pattern line."""
    out = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = line.split("=", 1)[0]
        if name != PATTERN_LINE:
            out.append(name)
    return out


def generate(names: list[str], db_host: str = "db") -> dict[str, str]:
    pg_password = secrets.token_urlsafe(24)  # urlsafe alphabet needs no escaping inside the DATABASE_URL
    values = {
        "POSTGRES_PASSWORD": pg_password,
        "DATABASE_URL": f"postgresql://gaconsole:{pg_password}@{db_host}:5432/gaconsole",
        "GC_JWT_SECRET": secrets.token_urlsafe(48),
        "GC_KEK_ID": KEK_ID,
        f"GC_KEK_{KEK_ID}": base64.b64encode(secrets.token_bytes(32)).decode(),
        "TELEMETRY_HASH_KEY": secrets.token_urlsafe(32),
        "GC_UPLOAD_DIR": "/data/uploads",
        "GC_UPLOAD_MAX_BYTES": str(200 * 1024 * 1024),
        "GC_CORS_ORIGIN": "http://localhost:3000",
        "NEXT_PUBLIC_API_MODE": "real",
        "NEXT_PUBLIC_API_URL": "http://localhost:8000",
    }
    missing = [n for n in names if n not in values]
    if missing:
        raise SystemExit("dev_env: no generator for " + ", ".join(missing))
    return values


def write_env(path: Path, example: Path = ROOT / ".env.example", db_host: str = "db") -> list[str]:
    """Create `path` (mode 0600). Returns the names written, never the values."""
    if path.exists():
        raise SystemExit(f"{path} already exists; not overwriting it (delete it first to regenerate)")
    values = generate(example_names(example.read_text()), db_host)
    path.write_text("# generated by scripts/dev_env.py for local development only; never commit\n"
                    + "".join(f"{k}={v}\n" for k, v in values.items()))
    path.chmod(0o600)
    return list(values)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--path", default=str(ROOT / ".env"))
    ap.add_argument("--db-host", default="db", help="host of the database in DATABASE_URL (compose: db; no Docker: localhost)")
    a = ap.parse_args(argv)
    names = write_env(Path(a.path), db_host=a.db_host)
    print(f"wrote {a.path}: {len(names)} variables ({', '.join(names)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
